spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
        one-indexed-parameters: true  # start with 1
  datasource:
    url : jdbc:h2:mem:blog
    username: sa
    password:
    driver-class-name: org.h2.Drivergi